name: Auto Update Course Database

on:
  # Run every Sunday at 2 AM UTC
  schedule:
    - cron: '0 2 * * 0'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to master (for testing)
  push:
    branches:
      - master
    paths:
      - 'scrape_courses.py'
      - 'auto_update.py'

jobs:
  update-courses:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
      
      - name: Run course scraper
        id: scrape
        run: |
          python auto_update.py
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet courses_database.json; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add courses_database.json miva_courses_full.json CHANGELOG.md .courses_hash.txt
          if [ -f CHANGELOG.md ]; then
                git add CHANGELOG.md
          fi
          git commit -m "chore: auto-update course database [skip ci]"
          git push
      
      - name: Create release (if changes detected)
        if: steps.changes.outputs.has_changes == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Course Database Update ${{ github.run_number }}
          body: |
            Automated course database update
            
            See CHANGELOG.md for details.
          draft: false
          prerelease: false
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: course-data
          path: |
            courses_database.json
            miva_courses_full.json
            CHANGELOG.md
            scraper.log
          retention-days: 30
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "Course update failed! Check logs."